services:
  nginx:
    image: nginx:1.26.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vite
      - spring
    restart: always
    networks:
      - app

  vite:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    expose:
      - 5173
    restart: always
    networks:
      - app

  spring:
    image: eclipse-temurin:17
    container_name: spring
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend/build/libs:/app
    command: ["java", "-jar", "onboarding-0.0.1-SNAPSHOT.jar"]
    networks:
      - app

networks:
  app:
    driver: bridge
