spring:
  application:
    name: jpa
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://kernel360.cbwucismyx0x.ap-northeast-2.rds.amazonaws.com:3306/mydb?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kernel360_5
    password: "6q]95+e~vmoCQkJu)T}:"
  output:
    ansi:
      enabled: always
